######
# This file includes the code to output a private confidence interval, using private mean 
# and variance estimators generated by Algorithm 2 Noisy Mean and Variance and simulation
# as introduced in Algorithm 3. 
######

#install.packages("rmutil")
library('rmutil')

############
# The function priv_ci() takes up to 6 parameters and returns a differentially private
# confidence interval: 
#   db:   Normally distributed sample data as a vector of numbers. 
#   a:    Significance level (set a = 0.05, the function outputs 95% confidence interval).
#   e:    Privacy parameter epsilon.
#   xmin: Given lower bound of the data range.
#   xmax: Given upper bound of the data range.
#   p:    Allocation of the privacy parameter epsilon. 100p% of the privacy budget is consumed
#         by generating the private mean; the rest is consumed by generating the private
#         variance. Set in default to the optimized value. 
############

priv_ci <- function(rep, db, a, e, xmin, xmax, p = .8) {
  e1 <- p*e
  e2 <- (1 - p)*e
  n <- length(db)
  db[db < xmin] <- xmin
  db[db > xmax] <- xmax
  width <- (xmax - xmin)
  
  m <- mean(db) + rlaplace(1, 0, width/(e1 * n))
  std <- sqrt(max(0, var(db) + rlaplace(1, 0, width^2/(n * e2))))
  if(std == 0) {
    return(c(m + qlaplace(a/2, 0, width/(e1 * n)), 
             m + qlaplace(1 - a/2, 0, width/(e1 * n))))
  }

  # Confidence interval simulation, as algorithm 3 SIM in the paper
  sims <- rnorm(1000, 0, std / sqrt(n)) + rlaplace(1000, 0, width/(e1 * n))
  moe <- diff(quantile(sims, c(a/2, 1 - a/2)))/2
  # print(moe)
  
  return(c(m - moe, m + moe))
}