######
# This file includes the code to output a private confidence interval, using private mean 
# and variance estimators generated by Algorithm 4 Noisy Absolute Deviation and simulation
# as introduced in Algorithm 3. 
######

#install.packages("rmutil")
library('rmutil')

############
# The function noisy_abs_SE() takes 3 parameters and returns a differentially private
# mean absolute deviation: 
#   data:     sample data as a vector of numbers. 
#   epsilon:  Privacy parameter epsilon. 
#   range:    Given data range. 
############
noisy_abs_SE <- function(data, epsilon, range){
  n <- length(data)
  avg <- mean(data) 
  priv_SE <- mean(abs(data - avg)) + rlaplace(1, 0, (2 * range) / (epsilon * n))
  return(priv_SE * sqrt(pi / 2))
}

############
# The function priv_abs_sd_ci() takes up to 6 parameters and returns a differentially private
# confidence interval: 
#   db:       Normally distributed sample data as a vector of numbers. 
#   a:        Significance level (set a = 0.05, the function outputs 95% confidence interval).
#   epsilon:  Privacy parameter epsilon.
#   xmin:     Given lower bound of the data range.
#   xmax:     Given upper bound of the data range.
#   rho:      Allocation of the privacy parameter epsilon. 100p% of the privacy budget is consumed
#             by generating the private mean; the rest is consumed by generating the private
#             variance. Set in default to the optimized value. 
############
priv_abs_sd_ci <- function(rep, db, a, epsilon, xmin, xmax, rho = .85) {
  n <- length(db)
  db[db < xmin] <- xmin
  db[db > xmax] <- xmax
  width <- (xmax - xmin)
  
  m <- mean(db) + rlaplace(1, 0, width/(epsilon * rho * n))
  std <- noisy_abs_SE(db, epsilon * (1 - rho), width)
  if(std <= 0) {
    return(c(m + qlaplace(a/2, 0, width/(epsilon * rho)/n), 
             m + qlaplace(1 - a/2, 0, width/(epsilon * rho)/n)))
  }
  
  sims <- rnorm(1000, 0, std/sqrt(n)) + rlaplace(1000, 0, width/(epsilon * rho * n))
  
  moe <- diff(quantile(sims, c(a/2, 1 - a/2)))/2
  # print(moe)
  return(c(m - moe, m + moe))
}
